name: Generate Event PNGs

on:
  schedule:
    - cron: '0 * * * *'   # Every hour
    - cron: '0 0 * * *'   # Midnight reset
  workflow_dispatch:      # Allows manual trigger

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Take screenshot
        run: node screenshot.js

      - name: Cleanup old images if midnight
        if: github.event.schedule == '0 0 * * *'
        run: rm -f output/*.png

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.png
          git commit -m "Update screenshot: $(date)"
          git push
