name: Update Events JSON

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch and save events
        run: node fetch-events.js

      - name: Commit & Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add events.json
          git commit -m "Update events.json" || echo "No changes"
          git push
